Name="4sight"

ThemeDescripton="A theme intending to emulate the 4sight workspace environment as closely as possible."

ThemeAuthor=""

Look = flat

OpaqueMove=1
OpaqueResize=0
GrabRootWindow=0

TitleButtonsLeft="i"
TitleButtonsRight="x"

TitleBarJustify=0
TitleBarHeight=24

TitleBarJoinLeft=1

BorderSizeX=8
BorderSizeY=8
CornerSizeX=28
CornerSizeY=28

# DlgBorderSizeX=3
# DlgBorderSizeY=3

TaskBarJustify="left"
TrayIconMaxHeight=31
TaskBarGraphHeight=30
TaskBarClockLeds = 0
TaskbarKeepBelow 
ShowElipsis=1
TrayDrawBevel=1

# Hues

# Menu
ColorNormalMenu="#ffffff"
ColorActiveMenuItem="#000000"
ColorNormalMenuItemText="#000000"
ColorActiveMenuItemText="#ffffff"

# Desktop
DesktopBackgroundColor=	"#859DBC"

ColorNormalTitleBarText="#000000"
ColorActiveTitleBarText="#000000"

# ColorNormalBorder="#000000"
# ColorActiveBorder="#000000"

#Fonts

TitleFontName="-adobe-helvetica-bold-o-*-*-14-*-*-*-*-*-*-*"
MenuFontName="-adobe-helvetica-bold-o-*-*-14-*-*-*-*-*-*-*"
StatusFontName=
NormalButtonFontName="-adobe-helvetica-medium-r-*-*-14-*-*-*-*-*-*-*"
NormalTaskbarFontName="-adobe-helvetica-bold-o-*-*-14-*-*-*-*-*-*-*"
